config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'account' => 'users#account'
  post 'login' => 'users#login'
  delete 'logout' => 'users#logout'
  resources :users

  get 'answer_riddle' => 'riddles#show'
  post 'answer_riddle' => 'riddles#answer'
  get 'new_riddle' => 'riddles#new'
  post 'new_riddle' => 'riddles#create'
  resources :riddles
end

app/models/riddle.rb
class Riddle < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :question, presence: true
  validates :answer_1, presence: true
  validates :answer_2, presence: true
  validates :answer_3, presence: true
  validates :answer_4, presence: true
  validates :right_answer, inclusion: { in: 1..4 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :riddles, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8, maximum: 32 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UsersHelper
  include RiddlesHelper
end

app/controllers/riddles_controller.rb
class RiddlesController < ApplicationController
  before_action :logged_in_user

  def new
    @newRiddle = current_user.riddles.build
    @errorMsg = ""
    @successMsg = ""
  end

  def create
    @newRiddle = current_user.riddles.build(riddle_params)
    if @newRiddle.save
      @errorMsg = ""
      @successMsg = "Riddle successfully received. Do another."
      @newRiddle = current_user.riddles.build
    end
    render "new"
  end

  def show
    get_riddle
  end

  def answer
    if params[:answers].to_i == current_riddle.right_answer
      @errorMsg = ""
      @successMsg = "Correct!"
    else
      @errorMsg = "That was incorrect. Perhaps you should read more."
      @successMsg = ""
    end
    get_riddle
    render "show"
  end

  private

    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end

    def get_riddle
      rand_id = rand(Riddle.count + 1)
      @riddle = Riddle.where("id >= ?", rand_id).limit(1).order("id asc")[0]
      set_current_riddle(@riddle)
    end

    def riddle_params
      params.require(:riddle).permit(:question, :answer_1, :answer_2, :answer_3, :answer_4, :right_answer)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @newUser = User.new
    @errorMsg = ''
  end

  def create
    @newUser = User.new(user_params)
    if @newUser.save
      log_in @newUser
      redirect_to '/'
    else
      render 'account'
    end
  end

  def login
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to '/'
    else
      @newUser = User.new
      @errorMsg = 'Invalid email/password combination'
      render 'account'
    end
  end

  def logout
    log_out
    redirect_to '/'
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/riddles_helper.rb
module RiddlesHelper
  def set_current_riddle(riddle)
    session[:riddle_id] = riddle.id
  end
  
  def current_riddle
    Riddle.find_by(id: session[:riddle_id])
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riddle Me This</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">RMT</a>
      </div>
      <% if logged_in? %>
        <p class="navbar-text navbar-right"><strong><%= @current_user.name %></strong> <%= link_to "Sign out", logout_path, method: "delete", class: "navbar-link" %></p>
      <% end %>
    </div>
  </nav>

<%= yield %>

  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text"><em>Owned by The Riddler. All rights reserved.</em></p>
    </div>
  </nav>
</body>
</html>

app/views/riddles/new.html.erb
<div class="container">
  <%= render 'shared/error_messages' %>
  <%= render 'shared/success_messages' %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="page-header">
        <h1>Write a Riddle <small>and make it clever</small></h1>
      </div>
      <%= form_for(@newRiddle) do |f| %>
        <div class="field">
          <%= f.text_area :question, placeholder: "Riddle me this..." %>
        </div>

        <%= f.label :answer_1 %>
        <%= f.text_field :answer_1, class: 'form-control' %>

        <%= f.label :answer_2 %>
        <%= f.text_field :answer_2, class: 'form-control' %>

        <%= f.label :answer_3 %>
        <%= f.text_field :answer_3, class: 'form-control' %>

        <%= f.label :answer_4 %>
        <%= f.text_field :answer_4, class: 'form-control' %>

        <%= f.label :right_answer %>
        <%= f.select :right_answer, [[1,1], [2,2], [3,3], [4,4]], class: 'form-control' %>

        <%= f.submit "Submit", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/riddles/show.html.erb
<div class="container">
  <%= render 'shared/error_messages' %>
  <%= render 'shared/success_messages' %>
  <div class="page-header">
    <h1>Riddle me this...</h1>
  </div>
  <p><em><%= @riddle.question %></em></p>
  <form action="/answer_riddle" method="post">
    <div style="display:none">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="answers" id="answer1" value="1">
        <%= @riddle.answer_1 %>
      </label>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="answers" id="answer2" value="2">
        <%= @riddle.answer_2 %>
      </label>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="answers" id="answer3" value="3">
        <%= @riddle.answer_3 %>
      </label>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="answers" id="answer4" value="4">
        <%= @riddle.answer_4 %>
      </label>
    </div>
    <input class="btn btn-success" name="commit" type="submit" value="Submit" />
  </form>
</div>

app/views/shared/_error_messages.html.erb
<% if @newUser && @newUser.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@newUser.errors.count, "error") %>.
    </div>
    <ul>
    <% @newUser.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% elsif @newRiddle && @newRiddle.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@newRiddle.errors.count, "error") %>.
    </div>
    <ul>
    <% @newRiddle.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% elsif @errorMsg && !@errorMsg.empty? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= @errorMsg %>
    </div>
  </div>
<% end %>

app/views/shared/_success_messages.html.erb
<% if @successMsg && !@successMsg.empty? %>
  <div id="success_explanation">
    <div class="alert alert-success">
      <%= @successMsg %>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Riddle Me This, Earth</h1>
    <p>How many riddles can the smartest man on Earth come up with? The answer: not as many as the smartest man on Earth + the collective "intelligence" of the rest of the planet. My duels with the dark detective have left my well of witticisms dry. You will therefore create an account for this website, submit your best brain benders, and help me evaluate the submissions of others. Perform these tasks well, and you stand to receive shares in my future operations.</p>
    <p><em>-E. Nigma</em></p>
  </div>
</div>
<div class="container">
  <div class="row">
    <% if !logged_in? %>
      <div class="col-md-4 col-md-offset-4">
        <div class="page-header">
          <h1>
            Sign Up <small>or Sign In</small>
          </h1>
        </div>
        <a class="btn btn-success center-block" href="<%= account_path %>" role="button">Go &gt;</a>
      </div>
    <% else %>
      <div class="col-md-5">
        <div class="page-header">
          <h1>
            Submit a Riddle<br/>
            <small>Jokes are NOT Riddles</small>
          </h1>
        </div>
        <a class="btn btn-success center-block" href="<%= new_riddle_path %>" role="button">Go &gt;</a>
      </div>
      <div class="col-md-5 col-md-offset-2">
        <div class="page-header">
          <h1>
            Answer a Riddle<br/>
            <small>No Cheating</small>
          </h1>
        </div>
        <a class="btn btn-success center-block" href="<%= answer_riddle_path %>" role="button">Go &gt;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/users/account.html.erb
<div class="container">
  <%= render 'shared/error_messages' %>
  <div class="row">
    <div class="col-md-5">
      <div class="page-header">
        <h1>Sign In</h1>
      </div>
      <%= form_for(:session, url: login_path) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.submit "Sign in", class: "btn btn-success" %>
      <% end %>
    </div>
    <div class="col-md-5 col-md-offset-2">
      <div class="page-header">
        <h1>Sign Up</h1>
      </div>
      <%= form_for(@newUser) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create account", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>